DROP DATABASE IF EXISTS superheroe;
CREATE DATABASE superheroe CHARACTER SET utf8mb4;
USE superheroe;

CREATE TABLE creador (
  id_creador INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, 
  nombre VARCHAR(20) NOT NULL
);


CREATE TABLE personaje (
  id_personaje INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  nombre_real VARCHAR(20) NOT NULL,
  personaje VARCHAR(20) NOT NULL,
  inteligencia INT(10) NOT NULL,
  fuerza VARCHAR(10) NOT NULL,
  velocidad INT(11) NOT NULL,
  poder INT(11) NOT NULL,
  aparicion INT(11) NOT NULL,
  ocupacion VARCHAR(30) NULL,
  id_creador INT UNSIGNED NOT NULL,
  FOREIGN KEY (id_creador) REFERENCES creador(id_creador)
);

SELECT * 
	FROM CREADOR;
SELECT * 
	FROM PERSONAJE;
    /*
    HOLAAAAAAAAA
    */
INSERT INTO CREADOR ( NOMBRE) VALUES ('PABLO');
INSERT INTO CREADOR ( NOMBRE) VALUES ('MATIAS');
INSERT INTO CREADOR ( NOMBRE) VALUES ('MARTINA');
INSERT INTO CREADOR ( NOMBRE) VALUES ('JAVIER');
INSERT INTO CREADOR ( NOMBRE) VALUES ('NICOLAS'); 

INSERT INTO PERSONAJE (NOMBRE_REAL,PERSONAJE,INTELIGENCIA,FUERZA,VELOCIDAD,PODER,APARICION,OCUPACION,ID_CREADOR) VALUES ('PANZA','SUERPAN',100,'EXTREMA',150,3000,2560,'DESEMPLEADO',1);
INSERT INTO PERSONAJE (NOMBRE_REAL,PERSONAJE,INTELIGENCIA,FUERZA,VELOCIDAD,PODER,APARICION,OCUPACION,ID_CREADOR) VALUES ('SALCHICHA','SUPERPANCHO',3650,'MEDIA',2560,2500,1500,'EN DESGRACIA',2);

SELECT FUERZA FROM PERSONAJE WHERE NOMBRE_REAL <> 'SALCHICHA'; 


